### ISSUE TITLE
error loading domotcz configuration

### ISSUE THREAD

**Issue by maxverstappen** [hansworst24/Ticz#19]
In settings there is a setting in general setting Gridview. When I change it to 7 I get an error loading domotcz configuration when I start the app.
When i change it to 1 or 10 it works again normally. 
On a lumia930 in portrait mode

**Comment by hansworst24** [comment]
Hey Max !

Great win 😄 Can I get an autograph ??. That sounds like strange behavior on the GridView Column setting. Nevertheless I think having a minimum column count of 7 on a 930 in portrait mode would render all devices to be useless/unreadable ? I think on a 930 maybe 2 might be the maximum columns I'd go for. I implemented this setting more for desktop/laptop/tablet, where the screensize in width is considerably larger, and you could tune the screen to contain the maximum of devices that works for you. I just checked on my 830 and it _does_ show 7 columns...but doesn't really look nice...

In any case, although I wouldn't recommend using such an high value on a phone, I will take a look in the code, to see if there is something strange happening

**Comment by hansworst24** [comment]
![wp_ss_20160516_0001](https://cloud.githubusercontent.com/assets/7300919/15350675/ee352e1a-1cda-11e6-815e-0d4d7b9d943a.png)

wanted to add this screenshot. This is how it would look with 7 columns.... Does 2 columns work for you ?

**Comment by maxverstappen** [comment]
Autograph is on the way :-)

If the setting is 10 (Icon view) it works for me. I get 3 columns (strange not) and 5 in landscape view

Most other settings I get the connections errors

The same error occurs if I switch the favourites is switched off.

**Comment by hansworst24** [comment]
ok, I did some testing and was at least able to let Ticz crash when playing with the GridView Minimum Columns settings while switching between rooms... Gonna have a look what is causing it 😃

**Comment by maxverstappen** [comment]
I think I found something else which can also be the cause.
I have the issue now also on my tablet when the connection is not on WiFi. 
I can test the connection in server settings ( on 4G) and Hurray is coming up. So the connection is working or not?
If I refresh the settings the error messsages also show up on my tablet/ via 4G
Went back to Wifi and the error still occurs.
Yes i am on basic _auth
Did a reset of the phone after restart it works again on Wifi after I went to server setting tested it and Ticz worked again.
Maybe the root cause is the same as issue #9

**Comment by maxverstappen** [comment]
Went back to Wifi and the error still occurs.
Yes i am on basic _auth

**Comment by hansworst24** [comment]
You're right, could be the same issue, although the guy who raised #9 doesn't seem to respond very well. The strange thing is that setting the GridView Minimum Columns has _nothing_ to do with Domoticz config :astonished: ...But we'll get there.

Just for my sake, could you post the output of `json.htm?type=command&param=getconfig` here, and provide a screenshot ?

**Comment by hansworst24** [comment]
Oh yeah : Something you can also test; I added a 'debug' feature in Ticz, which skips most of the app loading when a "Ticz" room is available in Domoticz. The idea was to use it if there were certain devices that might conflict somehow with Ticz : 
- Make a Room in Domoticz called "Ticz"
- Don't add any devices in this room yet
- Run Ticz. It should show a message related to "testing"
- Play with the GridView Minimum Columns while re-launching Ticz
- Let me know if it makes any difference (worse or better)

**Comment by maxverstappen** [comment]
"AllowWidgetOrdering" : false,
   "DashboardType" : 0,
   "DegreeDaysBaseTemperature" : 18.0,
   "FiveMinuteHistoryDays" : 3,
   "Latitude" : "51.439103",
   "Longitude" : "5.439668",
   "MobileType" : 1,
   "TempScale" : 1.0,
   "TempSign" : "C",
   "WindScale" : 1.0,
   "WindSign" : "m/s",
   "language" : "nl",
   "result" : {
      "EnableTabCustom" : false,
      "EnableTabDashboard" : true,
      "EnableTabFloorplans" : true,
      "EnableTabLights" : true,
      "EnableTabProxy" : false,
      "EnableTabScenes" : true,
      "EnableTabTemp" : true,
      "EnableTabUtility" : true,
      "EnableTabWeather" : true,
      "ShowUpdatedEffect" : false
   },
   "status" : "OK",
   "title" : "GetConfig"
}
Is this what you asked?

**Comment by hansworst24** [comment]
yep, that's the one. No issues I can see from that config that could cause the "Error loading Domoticz Config" Error. can you also post a screenshot of it ? From phone or tablet doesn't matter

**Comment by maxverstappen** [comment]
How can I upload it? I mailed it it

If I am on 4G and test the server settings I see on my router an incoming connection appearing. result hurray.
Closing the app and starting it again I see 10 incoming connections on my router

**Comment by hansworst24** [comment]
there's an attach files option in github, right below where you write your message :)
`Attach files by dragging & dropping or selecting them`
||
||
\/

Hmm, never bothered to look at amount of connections over WAN... could it be Firewall not liking that many of connections ?

**Comment by maxverstappen** [comment]
Get an error Something went really wrong, and we can’t process that file. 
![Uploading wp_ss_20160518_0005.png…]()

**Comment by maxverstappen** [comment]
##

**Comment by hansworst24** [comment]
I had the same issue uploading pics to github when using Edge. Try from a different browser. Can you (temporarily) try not to use SSL, and connect using HTTP only over 4G ? I'm using the same certificate, and added some - ignore SSL certificate issues - rules, but maybe there are some more to add...

**Comment by maxverstappen** [comment]
Browser did the trick
![wp_ss_20160518_0005](https://cloud.githubusercontent.com/assets/19385306/15454636/060eb4ae-203f-11e6-8447-8bd07d3c26c1.png)
![wp_ss_20160522_0001](https://cloud.githubusercontent.com/assets/19385306/15454640/1d4d94e6-203f-11e6-92b9-1a49d73ea284.png)

Reroute everything via port 80->8080. Checked it via a browser on my work. switched to 4G Changed the settings in Ticz. Checked the connection settings ->Hurray. got the last output above.

**Comment by maxverstappen** [comment]
![wp_ss_20160518_0003](https://cloud.githubusercontent.com/assets/19385306/15454702/75bd5840-2040-11e6-98bd-180152746c27.png)
![wp_ss_20160518_0004](https://cloud.githubusercontent.com/assets/19385306/15454701/75bb847a-2040-11e6-847b-745fc16d0899.png)
![wp_ss_20160518_0002](https://cloud.githubusercontent.com/assets/19385306/15454703/75bee4c6-2040-11e6-93ce-604bba28bfc3.png)
earlier errors

**Comment by hansworst24** [comment]
OK......... Just something that we need to check : You said you reroute everything from your Router port 80 to Domoticz IP port 8080 - correct ? By default 8080 is the non-SSL port Domoticz runs on. The SSL port is 443 by default.

So if you would want to connect with SSL, you'd have to reroute port 80 on your router to port 443 on Domoticz IP..right.. ?

Maybe I've misunderstood your config... but I think that's the cause !

**Comment by maxverstappen** [comment]
I disabled Use SSL and Ignore ssl Certificates is server settings. So plain http. Connection test resulted in a Hurray
Normally 443 is routed to the raspberry port 443 on the router.

**Comment by maxverstappen** [comment]
Today updated domoticz to 5163. Domoticz didn't start after update crashed immidiately.
Reverted to a backup (sd card image)version 2.4739, database of yesterday evening now it works. Will keep on testing. Will close the issue tommorow night

**Comment by maxverstappen** [comment]
Today it worked .... but not always. Then I get the same error messages as above.
But if I retry a few times it works again.
So it has improved (a lot) by restoring the backup of version 2.4739

**Comment by maxverstappen** [comment]
Just upgraded to stable 3.4834 no errors yet

**Comment by hansworst24** [comment]
Hmm...that's very strange... Was it running on a RPi ? Maybe it is sometimes slow in responding.. ? I'm runnin Domoticz on my N40L HP NAS so it has plenty of bandwidth/resources, but maybe that a Pi is more troublesome... Could even be worth testing setting up a test/temp Domoticz server on a laptop/PC or so...

The current hard-coded timeout is 5 seconds for any web requests from Ticz to another source... I'm looking into making that variable and provide a slider in the settings menu, to see if that is making any difference...

But for now I screwed too much up in the dev version of Ticz, so busy fixing my own errors, hahaha :smile:

**Comment by hansworst24** [comment]
Hey Max, still stable ?

**Comment by maxverstappen** [comment]
It works better but not allways
Past week I was on Aruba sometimes the errors occurs again. I will close the issue.tomorrow

```
  From: hansworst24 <notifications@github.com>
```

 To: hansworst24/Ticz Ticz@noreply.github.com 
Cc: maxverstappen roijmh@yahoo.com; State change state_change@noreply.github.com
 Sent: Tuesday, 7 June 2016, 20:34
 Subject: Re: [hansworst24/Ticz] error loading domotcz configuration (#19)

Hey Max, still stable ?—

**Comment by maxverstappen** [comment]
closed. but will keep testing.

**Comment by hansworst24** [comment]
I'll add a timeout setting which you can de- increase for http requests. Maybe increasing that will make it more stable
